/*
 * Copyright (c) 2023 @hanyazou
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef __DISAS_Z80_H__
#define __DISAS_Z80_H__

#include <stdio.h>
#include <disas.h>

const disas_inst_desc_t disas_z80[] = {
    { DISAS_OPERAND_0,  0x00,	"NOP"           },
    { DISAS_OPERAND_2,  0x01,   "LD BC,%04XH"   },
    { DISAS_OPERAND_0,  0x02,   "LD BC,A"       },
    { DISAS_OPERAND_0,  0x03,   "INC BC"        },
    { DISAS_OPERAND_0,  0x04,   "INC B"         },
    { DISAS_OPERAND_0,  0x05,   "DEC B"         },
    { DISAS_OPERAND_1,  0x06,   "LD B,%02XH"    },
    { DISAS_OPERAND_0,  0x07,   "RLCA"          },
    { DISAS_OPERAND_0,  0x08,   "EX AF,AF'"     },
    { DISAS_OPERAND_0,  0x09,   "ADD HL,BC"     },
    { DISAS_OPERAND_0,  0x0a,   "LD A,(BC)"     },
    { DISAS_OPERAND_0,  0x0b,   "DEC BC"        },
    { DISAS_OPERAND_0,  0x0c,   "INC C"         },
    { DISAS_OPERAND_0,  0x0d,   "DEC C"         },
    { DISAS_OPERAND_1,  0x0e,   "LD C,%02X"     },
    { DISAS_OPERAND_0,  0x0f,   "RRCA"          },

    { DISAS_OPERAND_1,  0x10,   "DJNZ,%d"       },
    { DISAS_OPERAND_2,  0x11,   "LD BC,%04XH"   },
    { DISAS_OPERAND_0,  0x12,   "LD (DE),A"     },
    { DISAS_OPERAND_0,  0x13,   "INC DE"        },
    { DISAS_OPERAND_0,  0x14,   "INC D"         },
    { DISAS_OPERAND_0,  0x15,   "DEC D"         },
    { DISAS_OPERAND_1,  0x16,   "LD D,%02XH"    },
    { DISAS_OPERAND_0,  0x17,   "RLA"           },
    { DISAS_OPERAND_1,  0x18,   "JR %d"         },
    { DISAS_OPERAND_0,  0x19,   "ADD HL,DE"     },
    { DISAS_OPERAND_0,  0x1a,   "LD A,(DE)"     },
    { DISAS_OPERAND_0,  0x1b,   "DEC DE"        },
    { DISAS_OPERAND_0,  0x1c,   "INC E"         },
    { DISAS_OPERAND_0,  0x1d,   "DEC E"         },
    { DISAS_OPERAND_1,  0x1e,   "LD E,%02X"     },
    { DISAS_OPERAND_0,  0x1f,   "RRA"           },

    { DISAS_OPERAND_1,  0x20,   "JR NZ,%d"      },
    { DISAS_OPERAND_2,  0x21,   "LD HL,%04XH"   },
    { DISAS_OPERAND_2,  0x22,   "LD (%04XH),HL" },
    { DISAS_OPERAND_0,  0x23,   "INC HL"        },
    { DISAS_OPERAND_0,  0x24,   "INC H"         },
    { DISAS_OPERAND_0,  0x25,   "DEC H"         },
    { DISAS_OPERAND_1,  0x26,   "LD H,%02XH"    },
    { DISAS_OPERAND_0,  0x27,   "DAA"           },
    { DISAS_OPERAND_1,  0x28,   "JR Z,%d"       },
    { DISAS_OPERAND_0,  0x29,   "ADD HL,HL"     },
    { DISAS_OPERAND_2,  0x2a,   "LD HL,(%04XH)" },
    { DISAS_OPERAND_0,  0x2b,   "DEC HL"        },
    { DISAS_OPERAND_0,  0x2c,   "INC L"         },
    { DISAS_OPERAND_0,  0x2d,   "DEC L"         },
    { DISAS_OPERAND_1,  0x2e,   "LD L,%02X"     },
    { DISAS_OPERAND_0,  0x2f,   "CPL"           },

    { DISAS_OPERAND_1,  0x30,   "JR NC,%d"      },
    { DISAS_OPERAND_2,  0x31,   "LD SP,%04XH"   },
    { DISAS_OPERAND_2,  0x32,   "LD (%04XH),A"  },
    { DISAS_OPERAND_0,  0x33,   "INC SP"        },
    { DISAS_OPERAND_0,  0x34,   "INC (HL)"      },
    { DISAS_OPERAND_0,  0x35,   "DEC (HL)"      },
    { DISAS_OPERAND_1,  0x36,   "LD (HL),%02XH" },
    { DISAS_OPERAND_0,  0x37,   "SCF"           },
    { DISAS_OPERAND_1,  0x38,   "JR C,%d"       },
    { DISAS_OPERAND_0,  0x39,   "ADD HL,SP"     },
    { DISAS_OPERAND_2,  0x3a,   "LD A,(%04XH)"  },
    { DISAS_OPERAND_0,  0x3b,   "DEC SP"        },
    { DISAS_OPERAND_0,  0x3c,   "INC A"         },
    { DISAS_OPERAND_0,  0x3d,   "DEC A"         },
    { DISAS_OPERAND_1,  0x3e,   "LD A,%02XH"    },
    { DISAS_OPERAND_0,  0x3f,   "CCF"           },

    { DISAS_OPERAND_0,  0x40,   "LD B,B"        },
    { DISAS_OPERAND_0,  0x41,   "LD B,C"        },
    { DISAS_OPERAND_0,  0x42,   "LD B,D"        },
    { DISAS_OPERAND_0,  0x43,   "LD B,E"        },
    { DISAS_OPERAND_0,  0x44,   "LD B,H"        },
    { DISAS_OPERAND_0,  0x45,   "LD B,L"        },
    { DISAS_OPERAND_0,  0x46,   "LD B,(HL)"     },
    { DISAS_OPERAND_0,  0x47,   "LD B,A"        },
    { DISAS_OPERAND_0,  0x48,   "LD C,B"        },
    { DISAS_OPERAND_0,  0x49,   "LD C,C"        },
    { DISAS_OPERAND_0,  0x4a,   "LD C,D"        },
    { DISAS_OPERAND_0,  0x4b,   "LD C,E"        },
    { DISAS_OPERAND_0,  0x4c,   "LD C,H"        },
    { DISAS_OPERAND_0,  0x4d,   "LD C,L"        },
    { DISAS_OPERAND_0,  0x4e,   "LD C,(HL)"     },
    { DISAS_OPERAND_0,  0x4f,   "LD C,A"        },

    { DISAS_OPERAND_0,  0x50,   "LD D,B"        },
    { DISAS_OPERAND_0,  0x51,   "LD D,C"        },
    { DISAS_OPERAND_0,  0x52,   "LD D,D"        },
    { DISAS_OPERAND_0,  0x53,   "LD D,E"        },
    { DISAS_OPERAND_0,  0x54,   "LD D,H"        },
    { DISAS_OPERAND_0,  0x55,   "LD D,L"        },
    { DISAS_OPERAND_0,  0x56,   "LD D,(HL)"     },
    { DISAS_OPERAND_0,  0x57,   "LD D,A"        },
    { DISAS_OPERAND_0,  0x58,   "LD E,B"        },
    { DISAS_OPERAND_0,  0x59,   "LD E,C"        },
    { DISAS_OPERAND_0,  0x5a,   "LD E,D"        },
    { DISAS_OPERAND_0,  0x5b,   "LD E,E"        },
    { DISAS_OPERAND_0,  0x5c,   "LD E,H"        },
    { DISAS_OPERAND_0,  0x5d,   "LD E,L"        },
    { DISAS_OPERAND_0,  0x5e,   "LD E,(HL)"     },
    { DISAS_OPERAND_0,  0x5f,   "LD E,A"        },

    { DISAS_OPERAND_0,  0x60,   "LD H,B"        },
    { DISAS_OPERAND_0,  0x61,   "LD H,C"        },
    { DISAS_OPERAND_0,  0x62,   "LD H,D"        },
    { DISAS_OPERAND_0,  0x63,   "LD H,E"        },
    { DISAS_OPERAND_0,  0x64,   "LD H,H"        },
    { DISAS_OPERAND_0,  0x65,   "LD H,L"        },
    { DISAS_OPERAND_0,  0x66,   "LD H,(HL)"     },
    { DISAS_OPERAND_0,  0x67,   "LD H,A"        },
    { DISAS_OPERAND_0,  0x68,   "LD L,B"        },
    { DISAS_OPERAND_0,  0x69,   "LD L,C"        },
    { DISAS_OPERAND_0,  0x6a,   "LD L,D"        },
    { DISAS_OPERAND_0,  0x6b,   "LD L,E"        },
    { DISAS_OPERAND_0,  0x6c,   "LD L,H"        },
    { DISAS_OPERAND_0,  0x6d,   "LD L,L"        },
    { DISAS_OPERAND_0,  0x6e,   "LD L,(HL)"     },
    { DISAS_OPERAND_0,  0x6f,   "LD L,A"        },

    { DISAS_OPERAND_0,  0x70,   "LD (HL),B"      },
    { DISAS_OPERAND_0,  0x71,   "LD (HL),C"     },
    { DISAS_OPERAND_0,  0x72,   "LD (HL),D"     },
    { DISAS_OPERAND_0,  0x73,   "LD (HL),E"     },
    { DISAS_OPERAND_0,  0x74,   "LD (HL),H"     },
    { DISAS_OPERAND_0,  0x75,   "LD (HL),L"     },
    { DISAS_OPERAND_0,  0x76,   "HALT"          },
    { DISAS_OPERAND_0,  0x77,   "LD (HL),A"     },
    { DISAS_OPERAND_0,  0x78,   "LD A,B"        },
    { DISAS_OPERAND_0,  0x79,   "LD A,C"        },
    { DISAS_OPERAND_0,  0x7a,   "LD A,D"        },
    { DISAS_OPERAND_0,  0x7b,   "LD A,E"        },
    { DISAS_OPERAND_0,  0x7c,   "LD A,H"        },
    { DISAS_OPERAND_0,  0x7d,   "LD A,L"        },
    { DISAS_OPERAND_0,  0x7e,   "LD A,(HL)"     },
    { DISAS_OPERAND_0,  0x7f,   "LD A,A"        },

    { DISAS_OPERAND_0,  0x80,   "ADD A,B"       },
    { DISAS_OPERAND_0,  0x81,   "ADD A,C"       },
    { DISAS_OPERAND_0,  0x82,   "ADD A,D"       },
    { DISAS_OPERAND_0,  0x83,   "ADD A,E"       },
    { DISAS_OPERAND_0,  0x84,   "ADD A,H"       },
    { DISAS_OPERAND_0,  0x85,   "ADD A,L"       },
    { DISAS_OPERAND_0,  0x86,   "ADD A,(HL)"    },
    { DISAS_OPERAND_0,  0x87,   "ADD A,A"       },
    { DISAS_OPERAND_0,  0x88,   "ADC A,B"       },
    { DISAS_OPERAND_0,  0x89,   "ADC A,C"       },
    { DISAS_OPERAND_0,  0x8a,   "ADC A,D"       },
    { DISAS_OPERAND_0,  0x8b,   "ADC A,E"       },
    { DISAS_OPERAND_0,  0x8c,   "ADC A,H"       },
    { DISAS_OPERAND_0,  0x8d,   "ADC A,L"       },
    { DISAS_OPERAND_0,  0x8e,   "ADC A,(HL)"    },
    { DISAS_OPERAND_0,  0x8f,   "ADC A,A"       },

    { DISAS_OPERAND_0,  0x90,   "SUB B"         },
    { DISAS_OPERAND_0,  0x91,   "SUB C"         },
    { DISAS_OPERAND_0,  0x92,   "SUB D"         },
    { DISAS_OPERAND_0,  0x93,   "SUB E"         },
    { DISAS_OPERAND_0,  0x94,   "SUB H"         },
    { DISAS_OPERAND_0,  0x95,   "SUB L"         },
    { DISAS_OPERAND_0,  0x96,   "SUB (HL)"      },
    { DISAS_OPERAND_0,  0x97,   "SUB A"         },
    { DISAS_OPERAND_0,  0x98,   "SBC A,B"       },
    { DISAS_OPERAND_0,  0x99,   "SBC A,C"       },
    { DISAS_OPERAND_0,  0x9a,   "SBC A,D"       },
    { DISAS_OPERAND_0,  0x9b,   "SBC A,E"       },
    { DISAS_OPERAND_0,  0x9c,   "SBC A,H"       },
    { DISAS_OPERAND_0,  0x9d,   "SBC A,L"       },
    { DISAS_OPERAND_0,  0x9e,   "SBC A,(HL)"    },
    { DISAS_OPERAND_0,  0x9f,   "SBC A,A"       },

    { DISAS_OPERAND_0,  0xa0,   "AND B"         },
    { DISAS_OPERAND_0,  0xa1,   "AND C"         },
    { DISAS_OPERAND_0,  0xa2,   "AND D"         },
    { DISAS_OPERAND_0,  0xa3,   "AND E"         },
    { DISAS_OPERAND_0,  0xa4,   "AND H"         },
    { DISAS_OPERAND_0,  0xa5,   "AND L"         },
    { DISAS_OPERAND_0,  0xa6,   "AND (HL)"      },
    { DISAS_OPERAND_0,  0xa7,   "AND A"         },
    { DISAS_OPERAND_0,  0xa8,   "XOR B"         },
    { DISAS_OPERAND_0,  0xa9,   "XOR C"         },
    { DISAS_OPERAND_0,  0xaa,   "XOR D"         },
    { DISAS_OPERAND_0,  0xab,   "XOR E"         },
    { DISAS_OPERAND_0,  0xac,   "XOR H"         },
    { DISAS_OPERAND_0,  0xad,   "XOR L"         },
    { DISAS_OPERAND_0,  0xae,   "XOR (HL)"      },
    { DISAS_OPERAND_0,  0xaf,   "XOR A"         },

    { DISAS_OPERAND_0,  0xb0,   "OR B"          },
    { DISAS_OPERAND_0,  0xb1,   "OR C"          },
    { DISAS_OPERAND_0,  0xb2,   "OR D"          },
    { DISAS_OPERAND_0,  0xb3,   "OR E"          },
    { DISAS_OPERAND_0,  0xb4,   "OR H"          },
    { DISAS_OPERAND_0,  0xb5,   "OR L"          },
    { DISAS_OPERAND_0,  0xb6,   "OR (HL)"       },
    { DISAS_OPERAND_0,  0xb7,   "OR A"          },
    { DISAS_OPERAND_0,  0xb8,   "CP B"          },
    { DISAS_OPERAND_0,  0xb9,   "CP C"          },
    { DISAS_OPERAND_0,  0xba,   "CP D"          },
    { DISAS_OPERAND_0,  0xbb,   "CP E"          },
    { DISAS_OPERAND_0,  0xbc,   "CP H"          },
    { DISAS_OPERAND_0,  0xbd,   "CP L"          },
    { DISAS_OPERAND_0,  0xbe,   "CP (HL)"       },
    { DISAS_OPERAND_0,  0xbf,   "CP A"          },

    { DISAS_OPERAND_0,  0xc0,   "RET NZ"        },
    { DISAS_OPERAND_0,  0xc1,   "POP BC"        },
    { DISAS_OPERAND_2,  0xc2,   "JP NZ,%04XH"   },
    { DISAS_OPERAND_2,  0xc3,   "JP %04XH"      },
    { DISAS_OPERAND_2,  0xc4,   "CALL NZ,%04XH" },
    { DISAS_OPERAND_0,  0xc5,   "PUSH BC"       },
    { DISAS_OPERAND_1,  0xc6,   "ADD A,%02XH"   },
    { DISAS_OPERAND_0,  0xc7,   "RST 00H"       },
    { DISAS_OPERAND_0,  0xc8,   "RET Z"         },
    { DISAS_OPERAND_0,  0xc9,   "RET"           },
    { DISAS_OPERAND_2,  0xca,   "JP Z,%04XH"    },
    { 0,                0xcb,   NULL            },
    { DISAS_OPERAND_2,  0xcc,   "CALL Z,%04XH"  },
    { DISAS_OPERAND_2,  0xcd,   "CALL %04XH"    },
    { DISAS_OPERAND_1,  0xce,   "ADC A,%02XH"   },
    { DISAS_OPERAND_0,  0xcf,   "RST 08H"       },

    { DISAS_OPERAND_0,  0xd0,   "RET NC"        },
    { DISAS_OPERAND_0,  0xd1,   "POP DE"        },
    { DISAS_OPERAND_2,  0xd2,   "JP NC,%04XH"   },
    { DISAS_OPERAND_1,  0xd3,   "OUT (%02XH),A" },
    { DISAS_OPERAND_2,  0xd4,   "CALL NC,%04XH" },
    { DISAS_OPERAND_0,  0xd5,   "PUSH DE"       },
    { DISAS_OPERAND_1,  0xd6,   "SUB %02XH"     },
    { DISAS_OPERAND_0,  0xd7,   "RST 10H"       },
    { DISAS_OPERAND_0,  0xd8,   "RET C"         },
    { DISAS_OPERAND_0,  0xd9,   "EXX"           },
    { DISAS_OPERAND_2,  0xda,   "JP C,%04XH"    },
    { DISAS_OPERAND_1,  0xdb,   "IN A,(%02XH)"  },
    { DISAS_OPERAND_2,  0xdc,   "CALL X,%04XH"  },
    { 0,                0xdd,   NULL            },
    { DISAS_OPERAND_1,  0xde,   "SBC A,%02XH"   },
    { DISAS_OPERAND_0,  0xdf,   "RST 18H"       },

    { DISAS_OPERAND_0,  0xe0,   "RET PO"        },
    { DISAS_OPERAND_0,  0xe1,   "POP HL"        },
    { DISAS_OPERAND_2,  0xe2,   "JP PO,%04XH"   },
    { DISAS_OPERAND_0,  0xe3,   "EX (SP),HL"    },
    { DISAS_OPERAND_2,  0xe4,   "CALL PO,%04XH" },
    { DISAS_OPERAND_0,  0xe5,   "PUSH HL"       },
    { DISAS_OPERAND_1,  0xe6,   "AND %02XH"     },
    { DISAS_OPERAND_0,  0xe7,   "RST 20H"       },
    { DISAS_OPERAND_0,  0xe8,   "RET PE"        },
    { DISAS_OPERAND_0,  0xe9,   "JP (HL)"       },
    { DISAS_OPERAND_2,  0xea,   "JP PE,%04XH"   },
    { DISAS_OPERAND_0,  0xeb,   "EX DE,HL"      },
    { DISAS_OPERAND_2,  0xec,   "CALL PE,%04XH" },
    { 0,                0xed,   NULL            },
    { DISAS_OPERAND_1,  0xee,   "XOR %02XH"     },
    { DISAS_OPERAND_0,  0xef,   "RST 28H"       },

    { DISAS_OPERAND_0,  0xf0,   "RET P"         },
    { DISAS_OPERAND_0,  0xf1,   "POP AF"        },
    { DISAS_OPERAND_2,  0xf2,   "JP P,%04XH"    },
    { DISAS_OPERAND_0,  0xf3,   "DI"            },
    { DISAS_OPERAND_2,  0xf4,   "CALL P,%04XH"  },
    { DISAS_OPERAND_0,  0xf5,   "PUSH AF"       },
    { DISAS_OPERAND_1,  0xf6,   "OR %02XH"      },
    { DISAS_OPERAND_0,  0xf7,   "RST 30H"       },
    { DISAS_OPERAND_0,  0xf8,   "RET M"         },
    { DISAS_OPERAND_0,  0xf9,   "LD SP,HL"      },
    { DISAS_OPERAND_2,  0xfa,   "JP M,%04XH"    },
    { DISAS_OPERAND_0,  0xfb,   "EI"            },
    { DISAS_OPERAND_2,  0xfc,   "CALL M,%04XH"  },
    { 0,                0xfd,   NULL            },
    { DISAS_OPERAND_1,  0xfe,   "CP %02XH"      },
    { DISAS_OPERAND_0,  0xff,   "RST 38H"       },

    { DISAS_END }
};

#endif  // __DISAS_Z80_H__
