#!/bin/bash

gen_chk_board_depend_h()
{
    echo
    echo "/* DO NOT EDIT */"
    echo "/* This file is auto generated by gen_chk_borad_dpend_h.sh */"
    echo
    echo "#ifndef BOARD_DEPENDENT_SOURCE"
    for port_group in A B C D E; do
        for register_name in PORT LAT TRIS WPU; do
            echo "#undef ${register_name}${port_group}"
            echo "#define ${register_name}${port_group} ERROR: Do not touch PIC ports directly here!"
        done
        for port_number in 0 1 2 3 4 5 6 7; do
            for register_name in R LAT TRIS WPU PPS; do
                echo "#undef ${register_name}${port_group}${port_number}"
                echo "#define ${register_name}${port_group}${port_number} ERROR: Do not touch PIC ports directly here!"
            done
        done
    done
    echo "#endif  // BOARD_DEPENDENT_SOURCE"
}

gen_chk_board_depend_h
