
/* DO NOT EDIT */
/* This file is auto generated by gen_chk_borad_dpend_h.sh */

#ifndef BOARD_DEPENDENT_SOURCE
#undef PORTA
#define PORTA ERROR: Do not touch PIC ports directly here!
#undef LATA
#define LATA ERROR: Do not touch PIC ports directly here!
#undef TRISA
#define TRISA ERROR: Do not touch PIC ports directly here!
#undef WPUA
#define WPUA ERROR: Do not touch PIC ports directly here!
#undef RA0
#define RA0 ERROR: Do not touch PIC ports directly here!
#undef LATA0
#define LATA0 ERROR: Do not touch PIC ports directly here!
#undef TRISA0
#define TRISA0 ERROR: Do not touch PIC ports directly here!
#undef WPUA0
#define WPUA0 ERROR: Do not touch PIC ports directly here!
#undef PPSA0
#define PPSA0 ERROR: Do not touch PIC ports directly here!
#undef RA1
#define RA1 ERROR: Do not touch PIC ports directly here!
#undef LATA1
#define LATA1 ERROR: Do not touch PIC ports directly here!
#undef TRISA1
#define TRISA1 ERROR: Do not touch PIC ports directly here!
#undef WPUA1
#define WPUA1 ERROR: Do not touch PIC ports directly here!
#undef PPSA1
#define PPSA1 ERROR: Do not touch PIC ports directly here!
#undef RA2
#define RA2 ERROR: Do not touch PIC ports directly here!
#undef LATA2
#define LATA2 ERROR: Do not touch PIC ports directly here!
#undef TRISA2
#define TRISA2 ERROR: Do not touch PIC ports directly here!
#undef WPUA2
#define WPUA2 ERROR: Do not touch PIC ports directly here!
#undef PPSA2
#define PPSA2 ERROR: Do not touch PIC ports directly here!
#undef RA3
#define RA3 ERROR: Do not touch PIC ports directly here!
#undef LATA3
#define LATA3 ERROR: Do not touch PIC ports directly here!
#undef TRISA3
#define TRISA3 ERROR: Do not touch PIC ports directly here!
#undef WPUA3
#define WPUA3 ERROR: Do not touch PIC ports directly here!
#undef PPSA3
#define PPSA3 ERROR: Do not touch PIC ports directly here!
#undef RA4
#define RA4 ERROR: Do not touch PIC ports directly here!
#undef LATA4
#define LATA4 ERROR: Do not touch PIC ports directly here!
#undef TRISA4
#define TRISA4 ERROR: Do not touch PIC ports directly here!
#undef WPUA4
#define WPUA4 ERROR: Do not touch PIC ports directly here!
#undef PPSA4
#define PPSA4 ERROR: Do not touch PIC ports directly here!
#undef RA5
#define RA5 ERROR: Do not touch PIC ports directly here!
#undef LATA5
#define LATA5 ERROR: Do not touch PIC ports directly here!
#undef TRISA5
#define TRISA5 ERROR: Do not touch PIC ports directly here!
#undef WPUA5
#define WPUA5 ERROR: Do not touch PIC ports directly here!
#undef PPSA5
#define PPSA5 ERROR: Do not touch PIC ports directly here!
#undef RA6
#define RA6 ERROR: Do not touch PIC ports directly here!
#undef LATA6
#define LATA6 ERROR: Do not touch PIC ports directly here!
#undef TRISA6
#define TRISA6 ERROR: Do not touch PIC ports directly here!
#undef WPUA6
#define WPUA6 ERROR: Do not touch PIC ports directly here!
#undef PPSA6
#define PPSA6 ERROR: Do not touch PIC ports directly here!
#undef RA7
#define RA7 ERROR: Do not touch PIC ports directly here!
#undef LATA7
#define LATA7 ERROR: Do not touch PIC ports directly here!
#undef TRISA7
#define TRISA7 ERROR: Do not touch PIC ports directly here!
#undef WPUA7
#define WPUA7 ERROR: Do not touch PIC ports directly here!
#undef PPSA7
#define PPSA7 ERROR: Do not touch PIC ports directly here!
#undef PORTB
#define PORTB ERROR: Do not touch PIC ports directly here!
#undef LATB
#define LATB ERROR: Do not touch PIC ports directly here!
#undef TRISB
#define TRISB ERROR: Do not touch PIC ports directly here!
#undef WPUB
#define WPUB ERROR: Do not touch PIC ports directly here!
#undef RB0
#define RB0 ERROR: Do not touch PIC ports directly here!
#undef LATB0
#define LATB0 ERROR: Do not touch PIC ports directly here!
#undef TRISB0
#define TRISB0 ERROR: Do not touch PIC ports directly here!
#undef WPUB0
#define WPUB0 ERROR: Do not touch PIC ports directly here!
#undef PPSB0
#define PPSB0 ERROR: Do not touch PIC ports directly here!
#undef RB1
#define RB1 ERROR: Do not touch PIC ports directly here!
#undef LATB1
#define LATB1 ERROR: Do not touch PIC ports directly here!
#undef TRISB1
#define TRISB1 ERROR: Do not touch PIC ports directly here!
#undef WPUB1
#define WPUB1 ERROR: Do not touch PIC ports directly here!
#undef PPSB1
#define PPSB1 ERROR: Do not touch PIC ports directly here!
#undef RB2
#define RB2 ERROR: Do not touch PIC ports directly here!
#undef LATB2
#define LATB2 ERROR: Do not touch PIC ports directly here!
#undef TRISB2
#define TRISB2 ERROR: Do not touch PIC ports directly here!
#undef WPUB2
#define WPUB2 ERROR: Do not touch PIC ports directly here!
#undef PPSB2
#define PPSB2 ERROR: Do not touch PIC ports directly here!
#undef RB3
#define RB3 ERROR: Do not touch PIC ports directly here!
#undef LATB3
#define LATB3 ERROR: Do not touch PIC ports directly here!
#undef TRISB3
#define TRISB3 ERROR: Do not touch PIC ports directly here!
#undef WPUB3
#define WPUB3 ERROR: Do not touch PIC ports directly here!
#undef PPSB3
#define PPSB3 ERROR: Do not touch PIC ports directly here!
#undef RB4
#define RB4 ERROR: Do not touch PIC ports directly here!
#undef LATB4
#define LATB4 ERROR: Do not touch PIC ports directly here!
#undef TRISB4
#define TRISB4 ERROR: Do not touch PIC ports directly here!
#undef WPUB4
#define WPUB4 ERROR: Do not touch PIC ports directly here!
#undef PPSB4
#define PPSB4 ERROR: Do not touch PIC ports directly here!
#undef RB5
#define RB5 ERROR: Do not touch PIC ports directly here!
#undef LATB5
#define LATB5 ERROR: Do not touch PIC ports directly here!
#undef TRISB5
#define TRISB5 ERROR: Do not touch PIC ports directly here!
#undef WPUB5
#define WPUB5 ERROR: Do not touch PIC ports directly here!
#undef PPSB5
#define PPSB5 ERROR: Do not touch PIC ports directly here!
#undef RB6
#define RB6 ERROR: Do not touch PIC ports directly here!
#undef LATB6
#define LATB6 ERROR: Do not touch PIC ports directly here!
#undef TRISB6
#define TRISB6 ERROR: Do not touch PIC ports directly here!
#undef WPUB6
#define WPUB6 ERROR: Do not touch PIC ports directly here!
#undef PPSB6
#define PPSB6 ERROR: Do not touch PIC ports directly here!
#undef RB7
#define RB7 ERROR: Do not touch PIC ports directly here!
#undef LATB7
#define LATB7 ERROR: Do not touch PIC ports directly here!
#undef TRISB7
#define TRISB7 ERROR: Do not touch PIC ports directly here!
#undef WPUB7
#define WPUB7 ERROR: Do not touch PIC ports directly here!
#undef PPSB7
#define PPSB7 ERROR: Do not touch PIC ports directly here!
#undef PORTC
#define PORTC ERROR: Do not touch PIC ports directly here!
#undef LATC
#define LATC ERROR: Do not touch PIC ports directly here!
#undef TRISC
#define TRISC ERROR: Do not touch PIC ports directly here!
#undef WPUC
#define WPUC ERROR: Do not touch PIC ports directly here!
#undef RC0
#define RC0 ERROR: Do not touch PIC ports directly here!
#undef LATC0
#define LATC0 ERROR: Do not touch PIC ports directly here!
#undef TRISC0
#define TRISC0 ERROR: Do not touch PIC ports directly here!
#undef WPUC0
#define WPUC0 ERROR: Do not touch PIC ports directly here!
#undef PPSC0
#define PPSC0 ERROR: Do not touch PIC ports directly here!
#undef RC1
#define RC1 ERROR: Do not touch PIC ports directly here!
#undef LATC1
#define LATC1 ERROR: Do not touch PIC ports directly here!
#undef TRISC1
#define TRISC1 ERROR: Do not touch PIC ports directly here!
#undef WPUC1
#define WPUC1 ERROR: Do not touch PIC ports directly here!
#undef PPSC1
#define PPSC1 ERROR: Do not touch PIC ports directly here!
#undef RC2
#define RC2 ERROR: Do not touch PIC ports directly here!
#undef LATC2
#define LATC2 ERROR: Do not touch PIC ports directly here!
#undef TRISC2
#define TRISC2 ERROR: Do not touch PIC ports directly here!
#undef WPUC2
#define WPUC2 ERROR: Do not touch PIC ports directly here!
#undef PPSC2
#define PPSC2 ERROR: Do not touch PIC ports directly here!
#undef RC3
#define RC3 ERROR: Do not touch PIC ports directly here!
#undef LATC3
#define LATC3 ERROR: Do not touch PIC ports directly here!
#undef TRISC3
#define TRISC3 ERROR: Do not touch PIC ports directly here!
#undef WPUC3
#define WPUC3 ERROR: Do not touch PIC ports directly here!
#undef PPSC3
#define PPSC3 ERROR: Do not touch PIC ports directly here!
#undef RC4
#define RC4 ERROR: Do not touch PIC ports directly here!
#undef LATC4
#define LATC4 ERROR: Do not touch PIC ports directly here!
#undef TRISC4
#define TRISC4 ERROR: Do not touch PIC ports directly here!
#undef WPUC4
#define WPUC4 ERROR: Do not touch PIC ports directly here!
#undef PPSC4
#define PPSC4 ERROR: Do not touch PIC ports directly here!
#undef RC5
#define RC5 ERROR: Do not touch PIC ports directly here!
#undef LATC5
#define LATC5 ERROR: Do not touch PIC ports directly here!
#undef TRISC5
#define TRISC5 ERROR: Do not touch PIC ports directly here!
#undef WPUC5
#define WPUC5 ERROR: Do not touch PIC ports directly here!
#undef PPSC5
#define PPSC5 ERROR: Do not touch PIC ports directly here!
#undef RC6
#define RC6 ERROR: Do not touch PIC ports directly here!
#undef LATC6
#define LATC6 ERROR: Do not touch PIC ports directly here!
#undef TRISC6
#define TRISC6 ERROR: Do not touch PIC ports directly here!
#undef WPUC6
#define WPUC6 ERROR: Do not touch PIC ports directly here!
#undef PPSC6
#define PPSC6 ERROR: Do not touch PIC ports directly here!
#undef RC7
#define RC7 ERROR: Do not touch PIC ports directly here!
#undef LATC7
#define LATC7 ERROR: Do not touch PIC ports directly here!
#undef TRISC7
#define TRISC7 ERROR: Do not touch PIC ports directly here!
#undef WPUC7
#define WPUC7 ERROR: Do not touch PIC ports directly here!
#undef PPSC7
#define PPSC7 ERROR: Do not touch PIC ports directly here!
#undef PORTD
#define PORTD ERROR: Do not touch PIC ports directly here!
#undef LATD
#define LATD ERROR: Do not touch PIC ports directly here!
#undef TRISD
#define TRISD ERROR: Do not touch PIC ports directly here!
#undef WPUD
#define WPUD ERROR: Do not touch PIC ports directly here!
#undef RD0
#define RD0 ERROR: Do not touch PIC ports directly here!
#undef LATD0
#define LATD0 ERROR: Do not touch PIC ports directly here!
#undef TRISD0
#define TRISD0 ERROR: Do not touch PIC ports directly here!
#undef WPUD0
#define WPUD0 ERROR: Do not touch PIC ports directly here!
#undef PPSD0
#define PPSD0 ERROR: Do not touch PIC ports directly here!
#undef RD1
#define RD1 ERROR: Do not touch PIC ports directly here!
#undef LATD1
#define LATD1 ERROR: Do not touch PIC ports directly here!
#undef TRISD1
#define TRISD1 ERROR: Do not touch PIC ports directly here!
#undef WPUD1
#define WPUD1 ERROR: Do not touch PIC ports directly here!
#undef PPSD1
#define PPSD1 ERROR: Do not touch PIC ports directly here!
#undef RD2
#define RD2 ERROR: Do not touch PIC ports directly here!
#undef LATD2
#define LATD2 ERROR: Do not touch PIC ports directly here!
#undef TRISD2
#define TRISD2 ERROR: Do not touch PIC ports directly here!
#undef WPUD2
#define WPUD2 ERROR: Do not touch PIC ports directly here!
#undef PPSD2
#define PPSD2 ERROR: Do not touch PIC ports directly here!
#undef RD3
#define RD3 ERROR: Do not touch PIC ports directly here!
#undef LATD3
#define LATD3 ERROR: Do not touch PIC ports directly here!
#undef TRISD3
#define TRISD3 ERROR: Do not touch PIC ports directly here!
#undef WPUD3
#define WPUD3 ERROR: Do not touch PIC ports directly here!
#undef PPSD3
#define PPSD3 ERROR: Do not touch PIC ports directly here!
#undef RD4
#define RD4 ERROR: Do not touch PIC ports directly here!
#undef LATD4
#define LATD4 ERROR: Do not touch PIC ports directly here!
#undef TRISD4
#define TRISD4 ERROR: Do not touch PIC ports directly here!
#undef WPUD4
#define WPUD4 ERROR: Do not touch PIC ports directly here!
#undef PPSD4
#define PPSD4 ERROR: Do not touch PIC ports directly here!
#undef RD5
#define RD5 ERROR: Do not touch PIC ports directly here!
#undef LATD5
#define LATD5 ERROR: Do not touch PIC ports directly here!
#undef TRISD5
#define TRISD5 ERROR: Do not touch PIC ports directly here!
#undef WPUD5
#define WPUD5 ERROR: Do not touch PIC ports directly here!
#undef PPSD5
#define PPSD5 ERROR: Do not touch PIC ports directly here!
#undef RD6
#define RD6 ERROR: Do not touch PIC ports directly here!
#undef LATD6
#define LATD6 ERROR: Do not touch PIC ports directly here!
#undef TRISD6
#define TRISD6 ERROR: Do not touch PIC ports directly here!
#undef WPUD6
#define WPUD6 ERROR: Do not touch PIC ports directly here!
#undef PPSD6
#define PPSD6 ERROR: Do not touch PIC ports directly here!
#undef RD7
#define RD7 ERROR: Do not touch PIC ports directly here!
#undef LATD7
#define LATD7 ERROR: Do not touch PIC ports directly here!
#undef TRISD7
#define TRISD7 ERROR: Do not touch PIC ports directly here!
#undef WPUD7
#define WPUD7 ERROR: Do not touch PIC ports directly here!
#undef PPSD7
#define PPSD7 ERROR: Do not touch PIC ports directly here!
#undef PORTE
#define PORTE ERROR: Do not touch PIC ports directly here!
#undef LATE
#define LATE ERROR: Do not touch PIC ports directly here!
#undef TRISE
#define TRISE ERROR: Do not touch PIC ports directly here!
#undef WPUE
#define WPUE ERROR: Do not touch PIC ports directly here!
#undef RE0
#define RE0 ERROR: Do not touch PIC ports directly here!
#undef LATE0
#define LATE0 ERROR: Do not touch PIC ports directly here!
#undef TRISE0
#define TRISE0 ERROR: Do not touch PIC ports directly here!
#undef WPUE0
#define WPUE0 ERROR: Do not touch PIC ports directly here!
#undef PPSE0
#define PPSE0 ERROR: Do not touch PIC ports directly here!
#undef RE1
#define RE1 ERROR: Do not touch PIC ports directly here!
#undef LATE1
#define LATE1 ERROR: Do not touch PIC ports directly here!
#undef TRISE1
#define TRISE1 ERROR: Do not touch PIC ports directly here!
#undef WPUE1
#define WPUE1 ERROR: Do not touch PIC ports directly here!
#undef PPSE1
#define PPSE1 ERROR: Do not touch PIC ports directly here!
#undef RE2
#define RE2 ERROR: Do not touch PIC ports directly here!
#undef LATE2
#define LATE2 ERROR: Do not touch PIC ports directly here!
#undef TRISE2
#define TRISE2 ERROR: Do not touch PIC ports directly here!
#undef WPUE2
#define WPUE2 ERROR: Do not touch PIC ports directly here!
#undef PPSE2
#define PPSE2 ERROR: Do not touch PIC ports directly here!
#undef RE3
#define RE3 ERROR: Do not touch PIC ports directly here!
#undef LATE3
#define LATE3 ERROR: Do not touch PIC ports directly here!
#undef TRISE3
#define TRISE3 ERROR: Do not touch PIC ports directly here!
#undef WPUE3
#define WPUE3 ERROR: Do not touch PIC ports directly here!
#undef PPSE3
#define PPSE3 ERROR: Do not touch PIC ports directly here!
#undef RE4
#define RE4 ERROR: Do not touch PIC ports directly here!
#undef LATE4
#define LATE4 ERROR: Do not touch PIC ports directly here!
#undef TRISE4
#define TRISE4 ERROR: Do not touch PIC ports directly here!
#undef WPUE4
#define WPUE4 ERROR: Do not touch PIC ports directly here!
#undef PPSE4
#define PPSE4 ERROR: Do not touch PIC ports directly here!
#undef RE5
#define RE5 ERROR: Do not touch PIC ports directly here!
#undef LATE5
#define LATE5 ERROR: Do not touch PIC ports directly here!
#undef TRISE5
#define TRISE5 ERROR: Do not touch PIC ports directly here!
#undef WPUE5
#define WPUE5 ERROR: Do not touch PIC ports directly here!
#undef PPSE5
#define PPSE5 ERROR: Do not touch PIC ports directly here!
#undef RE6
#define RE6 ERROR: Do not touch PIC ports directly here!
#undef LATE6
#define LATE6 ERROR: Do not touch PIC ports directly here!
#undef TRISE6
#define TRISE6 ERROR: Do not touch PIC ports directly here!
#undef WPUE6
#define WPUE6 ERROR: Do not touch PIC ports directly here!
#undef PPSE6
#define PPSE6 ERROR: Do not touch PIC ports directly here!
#undef RE7
#define RE7 ERROR: Do not touch PIC ports directly here!
#undef LATE7
#define LATE7 ERROR: Do not touch PIC ports directly here!
#undef TRISE7
#define TRISE7 ERROR: Do not touch PIC ports directly here!
#undef WPUE7
#define WPUE7 ERROR: Do not touch PIC ports directly here!
#undef PPSE7
#define PPSE7 ERROR: Do not touch PIC ports directly here!
#endif  // BOARD_DEPENDENT_SOURCE
